name: CI Pipeline

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint
        
    - name: Run pylint
      run: |
        pylint hello_world.py
        
  unit_test:
    name: Unit Testing
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Run unit tests
      run: |
        python3 -m unittest hello_world.py

  build_rpm:
    name: Build RPM Package
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install rpmbuild
      run: |
        sudo apt-get update
        sudo apt-get install rpm

    - name: Set up rpmbuild directory
      run: |
        mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

    - name: Copy spec file
      run: cp hello_world.spec ~/rpmbuild/SPECS/

    - name: Copy spec file
      run: cp hello_world.py ~/rpmbuild/SOURCES/

    - name: Build RPM package
      run: rpmbuild -ba ~/rpmbuild/SPECS/hello_world.spec

    - name: Build RPM package
      run: rpmbuild -ba ~/rpmbuild/SPECS/hello_world.spec

  upload:
    name: Upload Artifact
    runs-on: ubuntu-latest
    needs: [build_rpm]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Upload RPM artifact
      uses: actions/upload-artifact@v2
      with:
        name: rpm-package
        path: ~/rpmbuild/RPMS/
